### ISSUE TITLE
Неделя #4-5 Форма регистрации и авторизации пользователей в Qt

### ISSUE THREAD

**Issue by marginalprog** [SUAI-43dep-paoxt/TP2024#22]
- [x] Сделать макет формы регистрации и авторизации пользователей в Qt по дизайну из Figma (когда появится) 
- [x] Применить соответствующие стили для созданного макета

**Comment by marginalprog** [comment]
Реализована адаптивная форма регистрации и авторизации пользователей с переходом между ними. Кнопка "Регистрация"\"Вход" эмитирует сигнал успешного входа пользователя в систему, после чего открывается основное приложение.

![image](https://github.com/SUAI-43dep-paoxt/TP2024/assets/74926557/2678f12b-c074-4641-9eb2-017e9544315c)
![image](https://github.com/SUAI-43dep-paoxt/TP2024/assets/74926557/4135d89a-8f6c-437f-be9e-a5247e609fb0)

**Comment by yabudtospluseichas** [comment]
Применены стили к окну авторизации, согласно макетам из фигмы.
![image](https://github.com/SUAI-43dep-paoxt/TP2024/assets/161813803/61a0b7ad-83c1-4485-9cff-e68627417463)
![image](https://github.com/SUAI-43dep-paoxt/TP2024/assets/161813803/4ce8cd52-0b09-4d04-aed0-4694de3c48b0)
