### ISSUE TITLE
Создание виджетов QT для отображения динамических элементов 

### ISSUE THREAD

**Issue by Drsmail** [SUAI-43dep-paoxt/TP2024#46]
- [x]  Интегрировать ранее созданные решения в шаблоны виджетов QT
- [x]  Создать модульное решение, которое можно будет интегрировать в основной интерфейс
- [x] Определиться с набором цветов и шрифтов для этих элементов интерфейса

**Comment by Drsmail** [comment]
![image](https://github.com/SUAI-43dep-paoxt/TP2024/assets/60036448/6fae6965-a1f3-4b5e-8d94-1496c331c1d9)
Идея такая: берем текст, конвертируем его в псевдослучайное число с помощью операции хэширования, далее с помощью операции модуля получаем псевдослучайный индекс, по которому выбираем цвет элемента. Данное решение будет окрашивать элементы интерфейса для разных пользователей в одинаковые цвета, не храня при этом цвета элементов отдельно. Однако, оно не позволит пользователю выбирать цвет, так как он присваивается автоматически.

**Comment by Drsmail** [comment]
@marginalprog Можешь напомнить какой у нас шрифт, чтобы я скачал тот же самый?

**Comment by marginalprog** [comment]
@Drsmail Inter. Но его закинем потом в ресурсы, чтобы он вместе с приложением подтягивался

**Comment by Drsmail** [comment]
Обсудили на сегодняшнем совещании промежуточный результат, решили сделать картинку более гладкой, и добавить цвета
![image](https://github.com/SUAI-43dep-paoxt/TP2024/assets/60036448/fd26bc01-8734-4564-9258-041a9c5ea565)
Создал отдельную ветку, буду продолжать разработку.
