### ISSUE TITLE
Определить лучшие практики для работы с дизайном. Реализовать макет приложения в qt

### ISSUE THREAD

**Issue by marginalprog** [SUAI-43dep-paoxt/TP2024#6]
> - [x] 1. Установить Qt Design Studio и Qt creator, сравнить работоспособность и продуктивность при работе с ними
> - [x] 2. При выборе  Qt Design Studio конвертировать фигму в qt и qml
>###  крашится фигма при импорте дизайна с помощью qt bridge. Делаем в qt designer 
- [x] #14
- [x] 4. Разобраться как без загромождения импортировать стили (.qss) в виджеты
- [x] #10

**Comment by marginalprog** [comment]
п.п. 1-2 выполнены. 
Qt design studio только платная версия и не для использования в РФ. 
Qt bridge (плагин импорта фигмы в qt для qt design studio) работает некорректно - крашит и спамит фотками в макеты фигмы.
**Т. о. используем qt designer+любую удобную для вас ide и\или qt creator (там qt designer новее).**

**Comment by yabudtospluseichas** [comment]
п.п.4. Импорт стилей
Реализуется возможность чтения стилей из .qss файла, переписанного с .css (возможно данный вариант более оптимизирован).
Это один из способов импорта, также будут рассмотрены другие варианты для выявления более эффективной реализации импорта.
