### ISSUE TITLE
Реализовать в qt интерфейс по макетам из Figma (qt designer\ds\creator)

### ISSUE THREAD

**Issue by marginalprog** [SUAI-43dep-paoxt/TP2024#9]
- [x] 1. Вытянуть стили с figma
- [x] 2. Создать хранилище или устроить оптимальную систему работы с классами стилей (пока что наследование)
- [x] 3. Сделать связь qt и resource root
- [x] 4. Применить дизайн для главной страницы, разделённой на 4 блока:
> - [x] 4.1 - аватар и общие кнопки навигации
> - [x] 4.2 - списки, фильтры и деревья тегов
> - [x] 4.3 - списки задач, деревья задач
> - [x] 4.4 - описание задач (в т. ч. пустая страница с невыбранной задачей)

**Comment by yabudtospluseichas** [comment]
2. Создано хранилище для оптимальной системы работы с классами стилей (создан .qss файл со всеми стилями)
3. Сделана связь qt и resource root. Создан файл res.qrc, на его основе сгенерирован файл .py, который позволяет вытягивать необходимые ресурсы
4. Применен дизайн к главному окну: все лейблы, кнопки навигации, иконки, списки задач, деревья задач, описание задач, календарь, выбор тегов и пользователей.
![image](https://github.com/SUAI-43dep-paoxt/TP2024/assets/161813803/7fc75415-fa8f-43bd-96e9-4bb12f866958)
